# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

inputs:

  instance:
    description: input value that can be used to control which actions are run
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - name: load values from 1password vault
      uses: 1password/load-secrets-action@v2
      with:
        export-env: true
      env:
        DOCKER_LOGIN: op://empc-lab/svc-dockerhub/username
        DOCKER_PASSWORD: op://empc-lab/svc-dockerhub/password
        SNYK_TOKEN: op://empc-lab/svc-snyk/api-token

    - name: load cosign public key
      uses: ThoughtWorks-DPS/1password-action/write-to-file@main
      with:
        op-value: empc-lab/svc-cosign-public-key/notesPlain
        out-file: cosign.pub
