# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
run-name: static code analysis

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:

  static-code-analysis:
    name: static code analysis
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
