# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
run-name: test job container dev release

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:

  static-code-analysis:
    name: static code analysis
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
    with:
      image: twdps/gha-container-base-image
      op-version: 2.28.0
      snyk-version: 1.1291.0
      bats-version: 1.11.0
      hadolint-version: 2.12.0
      trivy-version: 0.51.1
      grype-version: 0.77.4
      cosign-version: 2.2.4
      syft-version: 1.4.1
      oras-version: 1.1.0
