# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
run-name: development build and release

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:

  dev-release:
    name: development build and release
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: twdps/gha-container-base-image
      op-version: 2.28.0
      snyk-version: 1.1291.0
      bats-version: 1.11.0
      hadolint-version: 2.12.0
      before-static-analysis: true
      snyk-scan: true
      snyk-severity-threshold: medium
      snyk-organization: twdps
      bats-test: true
      bats-run-container-name: gha-container-base-image
      bats-entry-point: /bin/ash
      bats-test-path: test/gha-container-base-image.bats
