# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: publish image

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:

  alpine-publish:
    name: publish alpine image
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/publish-container.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: twdps/gha-container-base-image
      sign-image: true
      sbom: true
      release-notes: true
      release-message: New release Alpine ThoughtWorks-DPS/gha-container-base-image
      before-publish: true

  ubuntu-publish:
    name: publish ubuntu image
    uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/publish-container.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: twdps/gha-container-base-image
      tag-annotation: ubuntu-
      sign-image: true
      sbom: true
      release-notes: true
      release-message: New release Ubuntu ThoughtWorks-DPS/gha-container-base-image
      before-publish: true